package com.sequra.disbursements;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Default test generated by Spring boot
 */
@SpringBootTest
class DisbursementsApplicationTests {

	@Test
	void contextLoads() {
	}

}
